### ISSUE TITLE
Nidhogg Spineshatter/Elusive

### ISSUE THREAD

**Issue by JaguarDTM** [xiv-stats/xiv-sim-documentation#11]
Our static tried using this to practice nidhogg placements and for some reason the Spineshatter and Elusive mechanics were placing to the party members flanks instead of front or rear.

**Comment by MillhioreF** [comment]
Known bug with the latest build, and will be fixed in the next. You can revert back to last year's build for the time being as a workaround.

**Comment by xiv-stats** [comment]
This should be fixed in the latest release.
